apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-cloud-serverless-2
  description: Tanzu Application Platform GUI Component
  tags:
    - app-accelerator
    - java
    - spring
    - cloud
    - serverless
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=spring-cloud-serverless-2'
spec:
  type: service
  lifecycle: production
  owner: default-team
  system: tap-gui
